apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1098"  # JMX exporter port
    spec:
      volumes:
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: >-
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.local.only=true
                -Dcom.sun.management.jmxremote.port=1099
                -Dcom.sun.management.jmxremote.rmi.port=1099
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -Djava.rmi.server.hostname=127.0.0.1
          ports:
            - containerPort: 8080
              name: http
       
        - name: jmx-exporter
          image: bitnami/jmx-exporter:1.3.0
          command:
            - "java"
            - "-jar"
            - "jmx_prometheus_standalone.jar"
            - "9400"
            - "/etc/jmx-exporter/exporter.yaml"
          ports:
          - containerPort: 9400
            name: jmx-metrics
          volumeMounts:
            - name: jmx-exporter-config
              mountPath: /etc/jmx-exporter