apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9400
      targetPort: 9400
      protocol: TCP
      name: jmx-metrics
  selector:
    app: {{ .Chart.Name }}